use_frameworks!
platform :ios, '9.0'

target 'listed-in-app' do
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'BSForegroundNotification'
  pod 'Cache'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'ObjectMapper'
  pod 'ReachabilitySwift'
  pod 'Reusable'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Bolts'
  pod 'GoogleSignIn'
  pod 'ActionSheetPicker-3.0'
  pod 'AEXML'
  pod 'SWXMLHash'
  pod 'SVProgressHUD'
  pod 'Firebase/AdMob'
  pod 'FBAudienceNetwork'
  pod 'Firebase/Database'
  pod 'MKDropdownMenu'
  pod 'SDCAlertView'
end
